[project]
name = "kinky-ir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "altair>=5.5.0",
    "marimo>=0.13.15",
    "pandas>=2.3.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
